const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');

const postsDirectory = path.join(__dirname, '../src/posts');
const outputFile = path.join(__dirname, '../src/posts/postsIndex.js');

function getReadingTime(content) {
    const wordsPerMinute = 200;
    const noOfWords = content.split(/\s/g).length;
    const minutes = noOfWords / wordsPerMinute;
    const readTime = Math.ceil(minutes);
    return `${readTime} min read`;
}

function getPosts() {
    if (!fs.existsSync(postsDirectory)) {
        console.log('No posts directory found.');
        return [];
    }

    const fileNames = fs.readdirSync(postsDirectory);
    const allPostsData = fileNames
        .filter(fileName => fileName.endsWith('.md'))
        .map(fileName => {
            const slug = fileName.replace(/\.md$/, '');
            const fullPath = path.join(postsDirectory, fileName);
            const fileContents = fs.readFileSync(fullPath, 'utf8');
            const { data, content } = matter(fileContents);

            return {
                slug,
                title: data.title || slug,
                date: data.date ? new Date(data.date).toISOString().split('T')[0] : 'No date', // Simple date formatting
                tags: data.tags || [],
                description: data.description || '',
                readTime: getReadingTime(content),
                file: fileName,
                content: content,
                ...data, // Include other frontmatter
            };
        });

    // Sort posts by date
    return allPostsData.sort((a, b) => {
        if (a.date < b.date) {
            return 1;
        } else {
            return -1;
        }
    });
}

const posts = getPosts();
const fileContent = `/* eslint-disable */
// This file is auto-generated by scripts/generate-posts.js
export default ${JSON.stringify(posts, null, 2)};
`;

fs.writeFileSync(outputFile, fileContent);
console.log(`Generated ${posts.length} posts in ${outputFile}`);
